builds:
- id: default
  env:
  - CGO_ENABLED=0
  main: main.go
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - 386

archives:
- id: default
  format: tar.gz
  files:
  - LICENSE
  - README.md
  - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512
